/**
 * vibe.js — Mistral Vibe adapter.
 *
 * Skills: .vibe/skills/<id>/ (project) or ~/.vibe/skills/<id>/ (global)
 * Agents: ~/.vibe/agents/<id>.toml (global only)
 */

import { existsSync, mkdirSync, symlinkSync, unlinkSync, readFileSync, writeFileSync, readdirSync } from 'fs';
import { resolve, relative } from 'path';
import { homedir } from 'os';
import { FrameworkAdapter } from './base.js';

export class VibeAdapter extends FrameworkAdapter {
  static id = 'vibe';
  static displayName = 'Mistral Vibe';
  static strategy = 'symlink';
  static contentTypes = ['skill', 'agent'];

  async detect(projectDir) {
    return existsSync(resolve(projectDir, '.vibe'));
  }

  _skillsBase(projectDir, scope) {
    return scope === 'global'
      ? resolve(homedir(), '.vibe/skills')
      : resolve(projectDir, '.vibe/skills');
  }

  _agentsBase() {
    return resolve(homedir(), '.vibe/agents');
  }

  async install(item, projectDir, scope, options = {}) {
    if (item.type === 'skill') {
      const targetBase = this._skillsBase(projectDir, scope);
      const targetPath = resolve(targetBase, item.id);
      if (options.dryRun) return { action: 'created', path: targetPath, details: 'dry-run' };
      if (existsSync(targetPath) && !options.force) return { action: 'skipped', path: targetPath, details: 'already exists' };

      mkdirSync(targetBase, { recursive: true });
      if (existsSync(targetPath)) try { unlinkSync(targetPath); } catch {}
      const source = item.sourceDir || resolve(options.almanacRoot, 'skills', item.id);
      symlinkSync(scope === 'global' ? source : relative(targetBase, source), targetPath);
      return { action: 'created', path: targetPath };
    }

    if (item.type === 'agent') {
      // Vibe uses .toml files for agents — generate a minimal config
      const agentsDir = this._agentsBase();
      const targetPath = resolve(agentsDir, `${item.id}.toml`);
      if (options.dryRun) return { action: 'created', path: targetPath, details: 'dry-run' };
      if (existsSync(targetPath) && !options.force) return { action: 'skipped', path: targetPath, details: 'already exists' };

      mkdirSync(agentsDir, { recursive: true });

      // Read agent metadata for TOML generation
      const description = item.description || item.id;
      const tools = (item.tools || []).map(t => `"${t}"`).join(', ');
      const tomlContent = `# Agent: ${item.id}
# Generated by agent-almanac CLI
# Source: ${item.sourcePath || 'unknown'}

[agent]
name = "${item.id}"
description = "${description}"
tools = [${tools}]

[agent.prompt]
system_prompt_id = "${item.id}"
`;
      writeFileSync(targetPath, tomlContent, 'utf8');
      return { action: 'created', path: targetPath };
    }

    return { action: 'skipped', path: '', details: `${item.type}s not supported` };
  }

  async uninstall(item, projectDir, scope, options = {}) {
    if (item.type === 'skill') {
      const targetPath = resolve(this._skillsBase(projectDir, scope), item.id);
      if (options.dryRun) return { action: 'removed', path: targetPath, details: 'dry-run' };
      if (!existsSync(targetPath)) return { action: 'skipped', path: targetPath, details: 'not installed' };
      unlinkSync(targetPath);
      return { action: 'removed', path: targetPath };
    }

    if (item.type === 'agent') {
      const targetPath = resolve(this._agentsBase(), `${item.id}.toml`);
      if (options.dryRun) return { action: 'removed', path: targetPath, details: 'dry-run' };
      if (!existsSync(targetPath)) return { action: 'skipped', path: targetPath, details: 'not installed' };
      unlinkSync(targetPath);
      return { action: 'removed', path: targetPath };
    }

    return { action: 'skipped', path: '', details: `${item.type}s not supported` };
  }

  async listInstalled(projectDir, scope) {
    const items = [];
    const skillsDir = this._skillsBase(projectDir, scope);
    if (existsSync(skillsDir)) {
      for (const name of readdirSync(skillsDir)) {
        items.push({ id: name, type: 'skill', path: resolve(skillsDir, name) });
      }
    }
    const agentsDir = this._agentsBase();
    if (existsSync(agentsDir)) {
      for (const name of readdirSync(agentsDir)) {
        if (name.endsWith('.toml')) {
          items.push({ id: name.replace(/\.toml$/, ''), type: 'agent', path: resolve(agentsDir, name) });
        }
      }
    }
    return items;
  }

  async audit(projectDir, scope) {
    const installed = await this.listInstalled(projectDir, scope);
    return {
      framework: VibeAdapter.displayName,
      ok: installed.length > 0 ? [`${installed.length} items installed`] : [],
      warnings: installed.length === 0 ? ['No Vibe content installed'] : [],
      errors: [],
    };
  }
}
