/**
 * sprites.js — Pixel art sprite data for campfire scenes.
 *
 * Each sprite is a 2D array of hex color strings (null = transparent).
 * Sprites are pure data — no rendering logic here.
 *
 * Aesthetic: dark fantasy RPG (Arcanum / Castlevania), warm palette.
 * Agent glyphs are downsampled from the viz pipeline's 512×512 WebP icons
 * (generated by viz/build-terminal-glyphs.js → cli/lib/glyph-data.json).
 */

import { createRequire } from 'module';
const require = createRequire(import.meta.url);
let glyphData;
try {
  glyphData = require('./glyph-data.json');
} catch {
  glyphData = { resolution: 0, agents: {} };
}

// ── Palette ─────────────────────────────────────────────────────────

// Fire colors (hot center → cool edges)
const W = '#FFEE88'; // white-hot core
const Y = '#FFCC33'; // bright yellow
const O = '#FF9922'; // mid-orange
const F = '#FF6B35'; // outer flame
const R = '#CC3300'; // deep red

// Structure
const B = '#8B4513'; // brown / log
const D = '#5C3317'; // dark wood
const K = '#3B2207'; // charcoal / ground
const S = '#444444'; // stone
const G = '#333333'; // dark stone

// Cold / ash
const A = '#666666'; // light ash
const H = '#555555'; // medium ash

// Agent figure (generic fallback)
const HD = '#8B7355'; // hood
const FC = '#D4A574'; // face / skin
const CK = '#6B5B3A'; // cloak
const CS = '#4A3A2A'; // cloak shadow
const AM = '#FFB347'; // amber accent (fire keeper)

const _ = null;

// ── Agent palette colors (cyberpunk) ────────────────────────────────
// Sourced from viz/dist/data/palette-colors.json — one color per agent.

const AGENT_COLORS = {
  'acp-developer':              '#55ddbb',
  'adaptic':                    '#44ffcc',
  'advocatus-diaboli':          '#ff4433',
  'alchemist':                  '#ffaa33',
  'apa-specialist':             '#77aadd',
  'auditor':                    '#ff7744',
  'blender-artist':             '#ff8833',
  'chromatographer':            '#44ccdd',
  'citizen-entomologist':       '#88dd55',
  'claw-polisher':              '#66dd99',
  'cli-developer':              '#55ccaa',
  'code-reviewer':              '#ff66aa',
  'conservation-entomologist':  '#66cc33',
  'contemplative':              '#c4b5fd',
  'designer':                   '#ff88dd',
  'devops-engineer':            '#00ff88',
  'diffusion-specialist':       '#cc77ff',
  'dog-trainer':                '#ff9944',
  'etymologist':                '#ddbb66',
  'fabricator':                 '#55ccdd',
  'gardener':                   '#44bb66',
  'geometrist':                 '#44ffaa',
  'gxp-validator':              '#ff3399',
  'hiking-guide':               '#77cc55',
  'hildegard':                  '#88dd77',
  'ip-analyst':                 '#33ccff',
  'janitor':                    '#99aacc',
  'jigsawr-developer':          '#22ddaa',
  'kabalist':                   '#9966dd',
  'lapidary':                   '#88ccee',
  'librarian':                  '#8B7355',
  'logician':                   '#33ddff',
  'markovian':                  '#7799ff',
  'martial-artist':             '#ff4466',
  'mcp-developer':              '#00ddbb',
  'mlops-engineer':             '#bb77ff',
  'mycologist':                 '#aa77cc',
  'mystic':                     '#dd44ff',
  'nlp-specialist':             '#bb88ff',
  'number-theorist':            '#bbaaff',
  'physicist':                  '#ff7744',
  'polymath':                   '#eedd44',
  'project-manager':            '#ff8844',
  'prospector':                 '#ddaa33',
  'putior-integrator':          '#66dd88',
  'quarto-developer':           '#33ddcc',
  'r-developer':                '#00f0ff',
  'relocation-expert':          '#ffbb44',
  'security-analyst':           '#ff3333',
  'senior-data-scientist':      '#aa66ff',
  'senior-researcher':          '#ffaa00',
  'senior-software-developer':  '#44ddff',
  'senior-ux-ui-specialist':    '#66ffcc',
  'senior-web-designer':        '#ffdd00',
  'shaman':                     '#9944ff',
  'shapeshifter':               '#bb88ff',
  'shiny-developer':            '#3399ff',
  'skill-reviewer':             '#ff66bb',
  'spectroscopist':             '#dd88ff',
  'survivalist':                '#88cc44',
  'swarm-strategist':           '#aadd44',
  'taxonomic-entomologist':     '#55bb22',
  'tcg-specialist':             '#ff5577',
  'theoretical-researcher':     '#aabbff',
  'tour-planner':               '#ffaa55',
  'translator':                 '#55bbcc',
  'version-manager':            '#44ddaa',
  'web-developer':              '#ff6633',
};

// ── Color helpers ───────────────────────────────────────────────────

/**
 * Darken a hex color by a factor (0 = black, 1 = unchanged).
 * @param {string} hex - '#RRGGBB'
 * @param {number} factor - 0.0–1.0
 * @returns {string}
 */
function darken(hex, factor) {
  const r = Math.round(parseInt(hex.slice(1, 3), 16) * factor);
  const g = Math.round(parseInt(hex.slice(3, 5), 16) * factor);
  const b = Math.round(parseInt(hex.slice(5, 7), 16) * factor);
  return '#' + [r, g, b].map(c => c.toString(16).padStart(2, '0')).join('');
}

// ── Campfire: Burning ───────────────────────────────────────────────
// 16w x 14h — tall asymmetric flames, bright core, stone ring + logs

export const CAMPFIRE_BURNING = [
  [_,_,_,_,_,_,_,_,_,Y,_,_,_,_,_,_],
  [_,_,_,_,_,_,_,_,Y,W,_,_,_,_,_,_],
  [_,_,_,_,_,_,_,Y,W,Y,O,_,_,_,_,_],
  [_,_,_,_,_,_,Y,O,W,W,O,_,_,_,_,_],
  [_,_,_,_,_,F,O,Y,W,W,Y,F,_,_,_,_],
  [_,_,_,_,F,O,Y,W,Y,W,Y,O,F,_,_,_],
  [_,_,_,R,F,O,O,Y,Y,O,O,F,R,_,_,_],
  [_,_,R,R,F,O,O,O,O,O,F,F,R,_,_,_],
  [_,_,R,R,F,F,F,O,F,F,F,R,R,_,_,_],
  [_,S,R,R,R,R,F,F,F,R,R,R,S,_,_,_],
  [_,S,S,B,D,R,R,R,R,D,B,S,S,_,_,_],
  [S,G,D,D,B,B,K,K,B,B,D,D,G,S,_,_],
  [S,G,G,D,D,K,K,K,K,D,D,G,G,S,_,_],
  [_,G,G,S,S,S,K,K,S,S,S,G,G,_,_,_],
];

// ── Campfire: Embers ────────────────────────────────────────────────
// 16w x 10h — low glow, glowing coals, collapsed logs

export const CAMPFIRE_EMBERS = [
  [_,_,_,_,_,_,_,R,_,_,_,_,_,_,_,_],
  [_,_,_,_,_,_,R,F,R,_,_,_,_,_,_,_],
  [_,_,_,_,_,R,F,O,F,R,_,_,_,_,_,_],
  [_,_,_,R,R,R,F,F,F,R,R,R,_,_,_,_],
  [_,S,R,R,R,R,F,F,R,R,R,R,S,_,_,_],
  [_,S,S,B,D,D,R,R,D,D,B,S,S,_,_,_],
  [S,G,D,D,D,B,K,K,B,D,D,D,G,S,_,_],
  [S,G,D,D,B,B,K,K,B,B,D,D,G,S,_,_],
  [S,G,G,D,D,K,K,K,K,D,D,G,G,S,_,_],
  [_,G,G,S,S,S,K,K,S,S,S,G,G,_,_,_],
];

// ── Campfire: Cold ──────────────────────────────────────────────────
// 16w x 8h — grey ash mound, no warmth, dark stone ring

export const CAMPFIRE_COLD = [
  [_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_],
  [_,_,_,_,_,_,H,A,H,_,_,_,_,_,_,_],
  [_,_,_,_,H,H,A,A,A,H,_,_,_,_,_,_],
  [_,S,G,H,H,H,A,A,H,H,G,S,_,_,_,_],
  [_,S,S,G,D,D,K,K,D,D,G,S,S,_,_,_],
  [S,G,D,D,D,K,K,K,K,D,D,D,G,S,_,_],
  [S,G,G,D,D,K,K,K,K,D,D,G,G,S,_,_],
  [_,G,G,S,S,S,K,K,S,S,S,G,G,_,_,_],
];

// ── Agent Glyph Factory ─────────────────────────────────────────────

/** Glyph resolution from the generated data. */
export const GLYPH_SIZE = glyphData.resolution || 48;

/**
 * Create an agent glyph sprite from the downsampled viz pipeline icon.
 * Falls back to a colored diamond shape for agents without glyph data.
 *
 * @param {string} agentId - Agent identifier.
 * @param {boolean} [isLead=false] - Fire keeper gets amber accent at top-left.
 * @returns {(string|null)[][]} GLYPH_SIZE × GLYPH_SIZE sprite.
 */
export function createAgentGlyph(agentId, isLead = false) {
  const entry = glyphData.agents[agentId];
  const sprite = entry?.grid || entry; // supports both { grid, png } and bare array format

  if (Array.isArray(sprite)) {
    if (!isLead) return sprite;
    // Deep copy and add amber accent (3×3 block at top-left corner).
    const copy = sprite.map(row => [...row]);
    for (let r = 0; r < 3 && r < copy.length; r++) {
      for (let c = 0; c < 3 && c < copy[r].length; c++) {
        copy[r][c] = AM;
      }
    }
    return copy;
  }

  // Fallback: colored diamond for unknown agents.
  return buildFallbackGlyph(agentId);
}

/**
 * Get the base64 PNG for an agent's icon (for inline image rendering).
 * @param {string} agentId
 * @returns {string|null} Base64 PNG string, or null if unavailable.
 */
export function getAgentPng(agentId) {
  return glyphData.agents[agentId]?.png || null;
}

/**
 * Get the base64 PNG horizontal strip for a team (all members side by side).
 * @param {string} teamId
 * @returns {string|null} Base64 PNG string, or null if unavailable.
 */
export function getTeamStrip(teamId) {
  return glyphData.teams?.[teamId] || null;
}

/**
 * Get the base64 PNG for a campfire state.
 * For burning, returns the first frame. Use getCampfireFrames for animation.
 * @param {'burning'|'embers'|'cold'} state
 * @returns {string|null} Base64 PNG string, or null if unavailable.
 */
export function getCampfirePng(state) {
  const data = glyphData.campfires?.[state];
  if (!data) return null;
  return Array.isArray(data) ? data[0] : data;
}

/**
 * Get all animation frames for a campfire state.
 * Returns an array (multiple frames for burning, single-element for others).
 * @param {'burning'|'embers'|'cold'} state
 * @returns {string[]} Array of base64 PNG strings.
 */
export function getCampfireFrames(state) {
  const data = glyphData.campfires?.[state];
  if (!data) return [];
  return Array.isArray(data) ? data : [data];
}

function buildFallbackGlyph(agentId) {
  const size = GLYPH_SIZE || 8;
  const color = AGENT_COLORS[agentId] || CK;
  const shadow = darken(color, 0.35);
  const mid = Math.floor(size / 2);
  const grid = Array.from({ length: size }, () => new Array(size).fill(null));

  for (let r = 0; r < size; r++) {
    const dist = Math.abs(r - mid);
    const half = mid - dist;
    for (let c = mid - half; c <= mid + half; c++) {
      grid[r][c] = (c === mid - half || c === mid + half || r === 0 || r === size - 1)
        ? shadow : color;
    }
  }
  return grid;
}

// ── Lookup ──────────────────────────────────────────────────────────

/**
 * Get the campfire sprite for a given fire state.
 * @param {'burning'|'embers'|'cold'} state
 * @returns {(string|null)[][]}
 */
export function getCampfireSprite(state) {
  if (state === 'burning') return CAMPFIRE_BURNING;
  if (state === 'embers') return CAMPFIRE_EMBERS;
  return CAMPFIRE_COLD;
}
