/**
 * workflow-diagram-nodes.test.js — `scripts/check-workflow-diagram-nodes.js` (#590).
 *
 * Fixtures are real git repos, unlike this suite's neighbours. That is not incidental:
 * the tool enumerates sources with `git ls-files -co --exclude-standard` so that
 * `viz/node_modules/` and the gitignored `viz/renv/library/` are excluded by the repo's
 * own ignore rules rather than by a second list that could disagree with them. A plain
 * directory would leave the ignore behaviour — the part that produced a wrong count when
 * it was written as a filesystem walk — untested.
 *
 * `git init` only; nothing is committed. `-o` lists untracked files, so a fixture proves
 * the enumeration without a commit, and `.gitignore` is honoured either way.
 *
 * The load-bearing tests are the two directions of the comparison and the shape parser.
 * A `[`-only anchor reports five missing nodes on the real corpus where one is real,
 * because four ids render as `id(["…"])` — so `parses every node shape` is guarding a
 * measured failure, not a hypothetical one.
 */

import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';
import { rmTree } from './_tmp.js';

const REPO = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..');
const TOOL = join(REPO, 'scripts', 'check-workflow-diagram-nodes.js');

/** The two assignments the tool parses out of the generator, in their real form. */
const GENERATOR = [
  '#!/usr/bin/env Rscript',
  'workflow <- putior::put(',
  '  script_dir,',
  '  pattern = "\\\\.(js|R)$",',
  '  recursive = TRUE,',
  '  exclude = c("build-workflow\\\\.js$", "build-workflow\\\\.R$")',
  ')',
].join('\n');

const annotation = (id, extra = '') => `// put id:"${id}", label:"${id} label"${extra}\n`;

function diagram(nodes) {
  return [
    '%% Auto-generated by build-workflow.R (putior) — do not edit manually',
    'flowchart TD',
    '    subgraph app ["app.js"]',
    ...nodes.map((n) => `        ${n}`),
    '    end',
    '',
    '    %% Connections',
    '    a --> b',
  ].join('\n');
}

/**
 * A fixture repo.
 *
 * @param {{sources?: Record<string,string>, diagram?: string|null, generator?: string|null,
 *          ignore?: string}} spec
 */
function makeRoot(t, spec = {}) {
  const dir = mkdtempSync(join(tmpdir(), 'diagram-nodes-'));
  t.after(() => rmTree(dir));

  const git = spawnSync('git', ['-C', dir, 'init', '-q'], { encoding: 'utf8' });
  assert.equal(git.status, 0, `git init failed: ${git.stderr}`);

  const write = (rel, text) => {
    const abs = join(dir, rel);
    mkdirSync(dirname(abs), { recursive: true });
    writeFileSync(abs, text, 'utf8');
  };

  if (spec.generator !== null) write('viz/build-workflow.R', spec.generator ?? GENERATOR);
  if (spec.diagram !== null) write('viz/public/data/workflow.mmd', spec.diagram ?? diagram(['node_a["A"]']));
  if (spec.ignore) write('.gitignore', spec.ignore);
  for (const [rel, text] of Object.entries(spec.sources ?? { 'viz/js/a.js': annotation('node_a') })) {
    write(rel, text);
  }
  return dir;
}

function run(dir, extra = []) {
  const r = spawnSync(process.execPath, [TOOL, '--root', dir, ...extra], { encoding: 'utf8' });
  return r;
}

function runJson(dir, extra = []) {
  const r = run(dir, ['--json', ...extra]);
  assert.ok(r.status === 0 || r.status === 1, `unexpected exit ${r.status}: ${r.stderr}`);
  return { ...JSON.parse(r.stdout), status: r.status };
}

const kinds = (out) => out.findings.map((f) => `${f.kind}:${f.node}`).sort();

describe('check-workflow-diagram-nodes — the comparison', () => {
  it('is clean when the node sets agree', (t) => {
    const dir = makeRoot(t);
    const out = runJson(dir);
    assert.deepEqual(out.findings, []);
    assert.equal(out.status, 0);
    assert.equal(out.annotationsFound, 1);
    assert.equal(out.diagramNodes, 1);
  });

  it('flags an annotated id with no node in the diagram', (t) => {
    const dir = makeRoot(t, {
      sources: { 'viz/js/a.js': annotation('node_a') + annotation('node_b') },
    });
    const out = runJson(dir);
    assert.deepEqual(kinds(out), ['missing-node:node_b']);
    assert.equal(out.status, 1);
  });

  it('flags a diagram node that no source annotates', (t) => {
    const dir = makeRoot(t, { diagram: diagram(['node_a["A"]', 'node_gone["Gone"]']) });
    const out = runJson(dir);
    assert.deepEqual(kinds(out), ['orphan-node:node_gone']);
  });

  it('reports both directions in one run', (t) => {
    const dir = makeRoot(t, {
      sources: { 'viz/js/a.js': annotation('node_new') },
      diagram: diagram(['node_a["A"]']),
    });
    assert.deepEqual(kinds(runJson(dir)), ['missing-node:node_new', 'orphan-node:node_a']);
  });

  it('keys a finding on the NODE, not the file, so two in one file stay distinct', (t) => {
    // `check-debt-ratchet.js` keys a member on `file` + `kind`. Without the node in
    // `file`, these two collapse to one member and repairing either covers the other.
    const dir = makeRoot(t, {
      sources: { 'viz/js/a.js': annotation('node_a') + annotation('node_x') + annotation('node_y') },
    });
    const files = runJson(dir).findings.map((f) => f.file).sort();
    assert.deepEqual(files, ['viz/js/a.js::node_x', 'viz/js/a.js::node_y']);
  });
});

describe('check-workflow-diagram-nodes — the ruler', () => {
  it('parses every node shape, not just square brackets', (t) => {
    // `([` is `node_type:"input"` and `[[` is `"output"` — both live in the real
    // diagram. `{`, `(` are the shapes a regeneration could introduce and #601 blocks
    // observing; a narrow class would report their nodes as orphans.
    const ids = ['sq', 'dbl', 'stadium', 'round', 'rhombus'];
    const dir = makeRoot(t, {
      sources: { 'viz/js/a.js': ids.map((id) => annotation(id)).join('') },
      diagram: diagram([
        'sq["square"]',
        'dbl[["subroutine"]]',
        'stadium(["stadium"])',
        'round("round")',
        'rhombus{"decision"}',
      ]),
    });
    assert.deepEqual(runJson(dir).findings, []);
  });

  it('does not mistake a subgraph declaration for a node, spaced or unspaced', (t) => {
    // Pins the OUTCOME, and does not claim to cover `SKIP_PREFIX`: a mutant deleting
    // that list survives this suite, because the line anchor already rejects both forms.
    // The measured cell where the list matters is scan-anywhere + the unspaced form, and
    // the parser is not scan-anywhere. The checker's header records the enumeration; the
    // test is here so that a future parser change has something to break.
    const dir = makeRoot(t, {
      diagram: [
        'flowchart TD',
        '    subgraph build_data ["build-data.js"]',
        '        node_a["A"]',
        '    end',
        '    subgraph app["app.js"]',
        '    end',
      ].join('\n'),
    });
    assert.deepEqual(runJson(dir).findings, []);
  });

  it('ignores styling and connection lines', (t) => {
    const dir = makeRoot(t, {
      diagram: [
        'flowchart TD',
        '    node_a["A"]',
        '    node_a --> node_a',
        '  classDef inputStyle fill:#1a1a2e,stroke:#00ff88',
        '  class node_a inputStyle',
        '  style node_a fill:#fff',
      ].join('\n'),
    });
    assert.deepEqual(runJson(dir).findings, []);
  });

  it('mirrors the generator exclude list rather than restating it', (t) => {
    // build-workflow.R and build-workflow.js annotate themselves and are excluded from
    // their own scan. A checker that does not mirror that reports both as missing.
    const dir = makeRoot(t, {
      sources: {
        'viz/js/a.js': annotation('node_a'),
        'viz/build-workflow.js': annotation('invoke_putior'),
      },
      generator: `${GENERATOR}\n# put id:"generate_diagram", label:"self"\n`,
    });
    const out = runJson(dir);
    assert.deepEqual(out.findings, []);
    assert.deepEqual(out.excludes, ['build-workflow\\.js$', 'build-workflow\\.R$']);
  });

  it('reads every exclude literal, including one containing a parenthesis', (t) => {
    // The `[^)]*` capture this replaced stopped at the `)` INSIDE the second literal, kept the
    // first, and silently dropped the second — so the checker scanned a file the generator
    // excludes. Usually noisy; silent when the wrongly-scanned file annotates an id that is in
    // the diagram and nothing in scope annotates, which suppresses an orphan-node finding.
    const dir = makeRoot(t, {
      generator: [
        'workflow <- putior::put(',
        '  script_dir,',
        '  pattern = "\\\\.(js|R)$",',
        '  exclude = c("build-workflow\\\\.js$", "\\\\.(min)\\\\.js$")',
        ')',
      ].join('\n'),
      sources: {
        'viz/js/a.js': annotation('node_a'),
        'viz/js/vendor.min.js': annotation('node_a') + annotation('node_ghost'),
      },
    });
    const out = runJson(dir);
    assert.deepEqual(out.excludes, ['build-workflow\\.js$', '\\.(min)\\.js$']);
    assert.deepEqual(out.findings, []);
  });

  it('refuses an exclude vector holding anything but string literals', (t) => {
    const r = run(makeRoot(t, { generator: 'pattern = "\\\\.(js|R)$"\nexclude = c(SKIP_ME, "a$")\n' }));
    assert.equal(r.status, 2);
    assert.match(r.stderr, /not a double-quoted string literal/);
  });

  it('honours the generator file pattern', (t) => {
    const dir = makeRoot(t, {
      sources: {
        'viz/js/a.js': annotation('node_a'),
        'viz/scripts/helper.py': '# put id:"node_py", label:"python"\n',
      },
    });
    assert.deepEqual(runJson(dir).findings, []);
  });

  it('does not scan gitignored sources', (t) => {
    // The real failure this replaces: a filesystem walk reaches
    // `viz/renv/library/.../putior/examples/*.R`, which ships its own annotations.
    const dir = makeRoot(t, {
      sources: {
        'viz/js/a.js': annotation('node_a'),
        'viz/renv/library/putior/examples/demo.R': '# put id:"vendor_node", label:"vendored"\n',
      },
      ignore: 'renv/library/\nviz/renv/library/\n',
    });
    const out = runJson(dir);
    assert.deepEqual(out.findings, []);
    assert.equal(out.annotationsFound, 1);
  });

  it('sees an annotation in a file whose name git would quote', (t) => {
    // Without `-z`, `core.quotepath` renders this as `"viz/js/caf\303\251.js"` — surrounding
    // quotes and all — which fails the `$`-anchored pattern test, drops the file, and leaves the
    // gate reading clean over a real missing node. The silent direction.
    const dir = makeRoot(t, {
      sources: { 'viz/js/café.js': annotation('node_a') + annotation('node_accented') },
    });
    assert.deepEqual(kinds(runJson(dir)), ['missing-node:node_accented']);
  });

  it('reads annotations from R sources as well as JavaScript', (t) => {
    const dir = makeRoot(t, {
      sources: { 'viz/R/render.R': '# put id:"node_a", label:"draw"\n' },
    });
    assert.deepEqual(runJson(dir).findings, []);
  });
});

describe('check-workflow-diagram-nodes — refusals', () => {
  const refuses = (t, spec, needle, extra = []) => {
    const r = run(makeRoot(t, spec), extra);
    assert.equal(r.status, 2, `expected exit 2, got ${r.status}\n${r.stdout}`);
    assert.match(r.stderr, needle);
  };

  it('refuses when the generator is absent', (t) => {
    refuses(t, { generator: null }, /no generator at viz\/build-workflow\.R/);
  });

  it('refuses when the generator declares no pattern', (t) => {
    refuses(t, { generator: 'exclude = c("x$")\n' }, /no `pattern = /);
  });

  it('refuses when the generator declares two patterns', (t) => {
    // Which one selects source files is ambiguous, and picking the first silently is
    // how a checker's scope comes to differ from the generator's while both look right.
    refuses(t, { generator: `${GENERATOR}\nother <- put(x, pattern = "\\\\.py$")\n` }, /2 `pattern = /);
  });

  it('refuses when the generator declares no exclude vector', (t) => {
    refuses(t, { generator: 'pattern = "\\\\.(js|R)$"\n' }, /no `exclude = c/);
  });

  it('refuses when the exclude vector is empty', (t) => {
    refuses(t, { generator: 'pattern = "\\\\.(js|R)$"\nexclude = c()\n' }, /holds no string literals/);
  });

  it('refuses when no source file matches the pattern', (t) => {
    refuses(t, { sources: { 'viz/notes.md': 'nothing here' } }, /no viz\/ file matched/);
  });

  it('refuses when the sources carry no annotation at all', (t) => {
    refuses(t, { sources: { 'viz/js/a.js': 'export const x = 1;\n' } }, /found no `put id:/);
  });

  it('refuses when the diagram is absent', (t) => {
    refuses(t, { diagram: null }, /no diagram at/);
  });

  it('refuses when the diagram parses to zero nodes', (t) => {
    // The vacuity that matters most: an empty or re-syntaxed diagram would otherwise
    // report every annotation as a missing node — a huge, confident, wrong finding.
    refuses(t, { diagram: 'flowchart TD\n' }, /parsed to zero nodes/);
  });

  it('refuses outside a git repository', (t) => {
    const dir = mkdtempSync(join(tmpdir(), 'diagram-nodes-nogit-'));
    t.after(() => rmTree(dir));
    mkdirSync(join(dir, 'viz'), { recursive: true });
    writeFileSync(join(dir, 'viz', 'build-workflow.R'), GENERATOR, 'utf8');
    const r = run(dir);
    assert.equal(r.status, 2);
    assert.match(r.stderr, /git ls-files failed/);
  });

  it('refuses an annotation id the diagram parser cannot read', (t) => {
    // `3d_view` is a legal mermaid id and `put id:"…"` accepts it, but the line parser's id
    // alphabet does not. Reporting it `missing-node` would be a permanent false finding, and the
    // repair for a permanent finding is to RATCHET it — writing an instrument artifact into
    // debt-ratchet.yml as though it were debt. Refusing is the only answer that stays honest.
    const r = run(makeRoot(t, {
      sources: { 'viz/js/a.js': annotation('node_a') + annotation('3d_view') },
      diagram: diagram(['node_a["A"]', '3d_view["3D"]']),
    }));
    assert.equal(r.status, 2);
    assert.match(r.stderr, /annotates id "3d_view", which is outside the alphabet/);
  });

  it('refuses a flag given no value', (t) => {
    const r = spawnSync(process.execPath, [TOOL, '--root'], { encoding: 'utf8' });
    assert.equal(r.status, 2);
    assert.match(r.stderr, /--root requires a value/);
  });
});

describe('check-workflow-diagram-nodes — the report', () => {
  it('exits 0 under --warn while still naming the findings', (t) => {
    const dir = makeRoot(t, { sources: { 'viz/js/a.js': annotation('node_a') + annotation('node_b') } });
    const r = run(dir, ['--warn']);
    assert.equal(r.status, 0);
    assert.match(r.stdout, /WARN \[missing-node\] node_b/);
  });

  it('publishes the vocabulary and coverage fields the ratchet validates against', (t) => {
    // `assertNotVacuous` in check-debt-ratchet.js checks a slice's `kinds` and
    // `scanned_field` for membership in these, so dropping either turns a ratcheted
    // slice into a refusal rather than a silent vacuous pass.
    const out = runJson(makeRoot(t));
    assert.deepEqual(out.kinds, ['missing-node', 'orphan-node']);
    assert.deepEqual(out.scannedFields, ['sourceFilesScanned', 'annotationsFound']);
    assert.equal(typeof out.sourceFilesScanned, 'number');
  });

  it('publishes path and node beside the encoded key', (t) => {
    const dir = makeRoot(t, { sources: { 'viz/js/a.js': annotation('node_a') + annotation('node_b') } });
    const [finding] = runJson(dir).findings;
    assert.equal(finding.path, 'viz/js/a.js');
    assert.equal(finding.node, 'node_b');
    assert.equal(finding.file, 'viz/js/a.js::node_b');
  });
});
